### ISSUE TITLE
Faute d'orthographe

### ISSUE THREAD

**Issue by AHL67** [iglee42/NotEnoughtChest#1]
Il y a plusieurs coffres ajoutés par le mod, donc il devrait s'appeler "Not Enough Chests", à l'image de "Not Enough Items" ou "Not Enough Wands" par exemple.
Je sais que c'est le nom du projet et que parfois c'est impossible à changer, mais dans le doute...

**Comment by iglee42** [comment]
J'essayerai de le fixer pour la prochaine maj
