### ISSUE TITLE
Chests not created for all planks

### ISSUE THREAD

**Issue by WenXin20** [iglee42/NotEnoughtChest#2]
### Mod

Biomes O' Plenty & Regions Unxeplored.
Both of these mods adds willow planks, but only one chest is added for regions unxeplored, but not for biomes o plenty. This probably happens for any woods

### Mod Link

https://www.curseforge.com/minecraft/mc-mods/regions-unexplored

### Wood Type

Willow

**Comment by iglee42** [comment]
It's not a bug, this is a feature of the mod to avoid having conflicts with ids

**Comment by WenXin20** [comment]
You could include the mod id such as doing `nec:bop_willow_chest` to avoid that. This is what we do for Every Compat. Otherwise there would be a lot of chests missing.

**Comment by iglee42** [comment]
I will do that

**Comment by iglee42** [comment]
Fixed
