### ISSUE TITLE
[Texture] Pokecube AIO

### ISSUE THREAD

**Issue by WenXin20** [iglee42/NotEnoughtChest#3]
### Mod

Pokecube AIO

### Mod Link

https://www.curseforge.com/minecraft/mc-mods/pokecube-aoi

### Wood Type

All types are missing textures. There are also enigma, leppa, sitrus, nanab, oran, & pecha wood types that no chests are registered for.

**Comment by iglee42** [comment]
Chest will be registered and textures will be added

**Comment by WenXin20** [comment]
Thanks!

**Comment by iglee42** [comment]
Fixed
