### ISSUE TITLE
[Bug] Chests missing tags

### ISSUE THREAD

**Issue by WenXin20** [iglee42/NotEnoughtChest#4]
### Issue
- All chests are missing the block & item tags `forge:chests` and `forge:chests/wooden`. The item tags would allow recipe compat with other mods, and the block tag would allow for tag compat with other block tags that use `forge:chests` & `forge:chests/wooden`.

**Comment by iglee42** [comment]
The tag was added but the custom datapack wasn't registered , it will be fix in the next update

**Comment by WenXin20** [comment]
Thanks!
