### ISSUE TITLE
[Texture]

### ISSUE THREAD

**Issue by FreddyFazbender** [iglee42/NotEnoughtChest#6]
### Already Asked

- [x] Not Asked ?

### Mod

Vampirism

### Mod Link

https://www.curseforge.com/minecraft/mc-mods/vampirism-become-a-vampire

### Wood Type

Cursed Planks, Dark planks

**Comment by FreddyFazbender** [comment]
I'm making a build, but the mod has no textures at all. I only put one mod, but there are no textures for any chests.

**Comment by iglee42** [comment]
Good just wait the update for API update
