### ISSUE TITLE
All Chest Textures Missing in Seaopolis Submerged

### ISSUE THREAD

**Issue by DaEggy** [iglee42/NotEnoughtChest#7]
### Already Asked

- [X] Not Asked ?

### Mod

NotEnoughChests

### Mod Link

https://www.curseforge.com/minecraft/mc-mods/not-enough-chest

### Wood Type

White Colored, Light Gray Colored, Light Blue Colored, Blue Colored, Gray Colored, Pink Colored, Green Colored, Lime Colored, Yellow Colored, Magenta Colored, Purple Colored, Black Colored, Cyan Colored, Brown Colored, Red Colored, Orange Colored, Rubberwood, Oak, Spruce, Birch, Jungle, Acacia, Cherry, Dark Oak, Mangrove, Bamboo, Crimson, Warped

**Comment by iglee42** [comment]
Update the mod
