### ISSUE TITLE
"Would", "Upgrade Aquatic" and "Productive Trees" mods missing textures

### ISSUE THREAD

**Issue by TheBeatenBlue** [iglee42/NotEnoughtChest#8]
### Already Asked

- [X] Not Asked ?

### Mod

Would, Productive Trees, Upgrade Aquatic 

### Mod Link

https://www.curseforge.com/minecraft/mc-mods/would;   https://www.curseforge.com/minecraft/mc-mods/productivetrees;  https://www.curseforge.com/minecraft/mc-mods/upgrade-aquatic

### Wood Type

All (I think?)

**Comment by MLDEG** [comment]
Hi !
I just looked at the missing textures on the identified mods and there is really a lot of work to be done for the "productivetrees" mod
So it won't be done quickly, but it will be done!
Thanks for the report.

**Comment by TheBeatenBlue** [comment]
Don't worry mate, take your time. This mod is a lifesaver, as Quark made my modpack barely usable, and Not Enough Chests solves most issues with it :) 
Cheers!
